### ISSUE TITLE
model used in real world.

### ISSUE THREAD

**Issue by ZhoZhicheng** [leggedrobotics/iPlanner#3]
Hi, thanks for your great job. But I ran into some problems when I tried to apply iplanner on my own robot. I wonder if the model you use in real world is the same as in the simulation? If they are the same, are they the one you shared here? Thank you so much.

**Comment by MichaelFYang** [comment]
Thanks for your question. No, the model used in real-world settings needs additional real-world data for fine-tuning to adapt to the noise of the depth camera. We're not sharing the real-world fine-tuned model since the noise pattern for different cameras used is different. You may need to collect some real-world images you own and fine-tune the model before you apply it to your robot in real world environment. (See the instructions in the README file)
